global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # TruckPort Frontend monitoring
  - job_name: 'truckport-frontend'
    static_configs:
      - targets: ['truckport-frontend:80']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # TruckPort Backend API monitoring
  - job_name: 'truckport-backend'
    static_configs:
      - targets: ['truckport-backend:3000']
    metrics_path: '/api/health'
    scrape_interval: 15s
    scrape_timeout: 5s

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['truckport-db:5432']
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['truckport-redis:6379']
    scrape_interval: 30s

  # Nginx monitoring (if metrics are enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['truckport-frontend:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node.js application metrics (if available)
  - job_name: 'node-metrics'
    static_configs:
      - targets: ['truckport-backend:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
